# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = [
    'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
]

exec-on-workspace-change = ['/Users/grantcodes/.config/aerospace/scripts/pip-support.sh']


# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 50

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = true

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 8
inner.vertical =   8
outer.left =       8
outer.bottom =     8
outer.top =        8
outer.right =      8

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.main.binding]

# App shortcuts
ctrl-b = 'exec-and-forget open -n /Applications/Vivaldi.app'
ctrl-enter = 'exec-and-forget open -n /Applications/Ghostty.app'
ctrl-e = 'exec-and-forget open -n /Applications/Visual\ Studio\ Code.app'

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
ctrl-slash = 'layout tiles horizontal vertical'
ctrl-comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
ctrl-h = 'focus --boundaries-action wrap-around-the-workspace left'
ctrl-j = 'focus --boundaries-action wrap-around-the-workspace down'
ctrl-k = 'focus --boundaries-action wrap-around-the-workspace up'
ctrl-l = 'focus --boundaries-action wrap-around-the-workspace right'
ctrl-up = 'focus --boundaries-action wrap-around-the-workspace left'
ctrl-down = 'focus --boundaries-action wrap-around-the-workspace right'
ctrl-left = 'exec-and-forget aerospace workspace "$(aerospace list-workspaces --monitor mouse --visible)" && aerospace workspace prev'
ctrl-right = 'exec-and-forget aerospace workspace "$(aerospace list-workspaces --monitor mouse --visible)" && aerospace workspace next'
ctrl-q = 'close --quit-if-last-window'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
ctrl-shift-h = 'move left'
ctrl-shift-j = 'move down'
ctrl-shift-k = 'move up'
ctrl-shift-l = 'move right'
ctrl-shift-up = 'move left'
ctrl-shift-down = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
ctrl-shift-minus = 'resize smart -50'
ctrl-shift-equal = 'resize smart +50'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
ctrl-a = 'workspace primary'
ctrl-r = 'workspace secondary'
ctrl-1 = 'workspace primary'
ctrl-2 = 'workspace secondary'
ctrl-3 = 'workspace 3'
ctrl-4 = 'workspace 4'
ctrl-5 = 'workspace 5'
ctrl-6 = 'workspace 6'
ctrl-7 = 'workspace 7'
ctrl-8 = 'workspace 8'
ctrl-9 = 'workspace 9'
ctrl-n = 'summon-workspace notes'
ctrl-s = 'summon-workspace chat'
ctrl-t = 'summon-workspace terminal'


# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
ctrl-shift-a = 'move-node-to-workspace primary --focus-follows-window'
ctrl-shift-r = 'move-node-to-workspace secondary --focus-follows-window'
ctrl-shift-1 = 'move-node-to-workspace primary --focus-follows-window'
ctrl-shift-2 = 'move-node-to-workspace secondary --focus-follows-window'
ctrl-shift-3 = 'move-node-to-workspace 3 --focus-follows-window'
ctrl-shift-4 = 'move-node-to-workspace 4 --focus-follows-window'
ctrl-shift-5 = 'move-node-to-workspace 5 --focus-follows-window'
ctrl-shift-6 = 'move-node-to-workspace 6 --focus-follows-window'
ctrl-shift-7 = 'move-node-to-workspace 7 --focus-follows-window'
ctrl-shift-8 = 'move-node-to-workspace 8 --focus-follows-window'
ctrl-shift-9 = 'move-node-to-workspace 9 --focus-follows-window'
ctrl-shift-n = 'move-node-to-workspace notes --focus-follows-window'
ctrl-shift-s = 'move-node-to-workspace chat --focus-follows-window'
ctrl-shift-t = 'move-node-to-workspace terminal --focus-follows-window'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
ctrl-tab = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
ctrl-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# Automatic workspace handling
[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = 'move-node-to-workspace primary --focus-follows-window'

[[on-window-detected]]
if.app-id = 'com.todesktop.230313mzl4w4u92'
run = 'move-node-to-workspace primary --focus-follows-window'

#[[on-window-detected]]
#if.app-id = 'com.vivaldi.Vivaldi'
#run = 'move-node-to-workspace primary --focus-follows-window'

#[[on-window-detected]]
#if.app-id = 'com.mitchellh.ghostty'
#run = 'move-node-to-workspace terminal --focus-follows-window'
[[on-window-detected]]
if.app-id="com.mitchellh.ghostty"
run= ["layout tiling"]

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace chat --focus-follows-window'

[[on-window-detected]]
if.app-id = 'com.vivaldi.Vivaldi.app.ohflcoobaifidijbbdennjefionbfnkl'
run = 'move-node-to-workspace chat --focus-follows-window'

[[on-window-detected]]
if.app-id = 'md.obsidian'
run = 'move-node-to-workspace notes --focus-follows-window'

[[on-window-detected]]
if.app-id = 'org.mozilla.thunderbird'
run = 'move-node-to-workspace secondary --focus-follows-window'




